---
title: "Variación Entre-individuos y Sub-individuo"
author: "Raymond L. Tremblay"
date: "8/20/2021"
output:
  html_document:
    css: tutorial.css
    fig_caption: yes
    highlight: pygments
#  theme: simplex   To have the TOC in Red
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Variación: Definición

##### Patrones de variación

+ Geográfica
+ Poblacional
+ Individual
+ Sub-Individual

##### Causa de la variación

+ Genética
+ Ambiental
+ Plasticidad Fenotípica


Leer este articulo [Brushi 2003](PDF/2003AnnBotanyRoveri.pdf).
 
 Cuando lee el articulo concentrarse en las características morfológicas. 
 
 Preguntas guías:
       - ¿Cual son las variables morfológicas que se midieron? Menciona algunas (4-5)
       - ¿Qué quiere decir ***Mean*** y  ***s.d.***?
       - ¿Cual variable tiene mayor promedio?
       
¿Como uno puede evaluar la variación controlando para el promedio?

El problema de la relación positiva y variación.
       
 
### Coeficiente de Variación, CV
 
 El CV es un indice de variación qué es estandarizado, en otro palabra es comparable entre cambios en el promedio y unidades de medida (cm, me, km)
 
 Vea este enlace sobre el coeficiente de Variación, [CV](https://en.wikipedia.org/wiki/Coefficient_of_variation)
 
 La formula  básica es $$CV=\frac{sd}{\overline{x}},$$ donde **sd** es la desviación estándar, $$sd = \sqrt{\frac{1}{N-1} \sum_{i=1}^N (x_i - \overline{x})^2}$$
 
  
-------------------
  
  La hipótesis que vamos a comprobar es basado en la siguiente aseveración:
  
  1. la hojas captan la luz.
  2. El área de lamina pudiese afectar la capacidad de fotosíntesis.
  3. Las plantas pudiese adaptarse a los cambios lumínicos
  4. La hojas arriba de un árbol reciben más luz que las hoja abajo o adentro (cerca del tronco).
  
  
  Hipótesis alterna:  Existe Variación-Sub Individual y esta variación es diferente entre individuos.
  
  ¿Cual es la hipótesis nula?
  
  Ejercicio:
  
  Se recolectará hojas de 3 arboles de la misma especie, se medirá la siguiente características
  
  - el ancho de la hoja
  - el largo de la hoja
  
  La hojas se recolectará de la parta más alta del árbol (expuesto al sol) y la más abajo y adentro del árbol (expuesto en la sombra).
  
  + 40 mínimo hojas arriba
  + 40 mínimo hojas abajo
  
  
  
### Enlace para añadir los datos recolectados

##### Lab de Lunes sec 001, 3pm a 5.50pm.

LUNES: Presione aquí [Hoja_de Datos](https://docs.google.com/spreadsheets/d/1V3x81vW59nj_3wiutnvrITYicAEarDbLEy3mVbUQjp0/edit?usp=sharing)


#####  Lab de Martes sec 005, 12:00pm a 2:50pm.

MARTES: Presione aquí [Hoja_de Datos](https://docs.google.com/spreadsheets/d/1wNRbc0u9sNjdYF8ko6DyZ9H87IMp39fVktfUwbQChas/edit?usp=sharing)

***

Las especies muestradas

G1 = [*Tabebuia heterophylla*](https://en.wikipedia.org/wiki/Tabebuia_heterophylla)  
G2 = [*Cananga odorata*](https://en.wikipedia.org/wiki/Cananga_odorata)


***

Referencias:

a. [Conceptos generales sobre variación](PDF/Chapt3.pdf)
b. [Selective Pressure](PDF/pone.0074356.pdf)

Leer el capítulo #3 de este libro

c. [Multiplicity in Unity](PDF/Multiplicity in Unity Carlos Herrera.pdf)
 

## Próximo Lab: 
Presentación sobre variación [subindividual](Prresentation/Subindividual_variation.pdf)



## Comparación estadistica entre tres o más grupos en **MSExcel** o **Google sheet**

Cuando uno quiere comparar 3 o más grupos uno puede usar ANOVA para hacer las determinar si los grupos son significativamente diferente uno del otro.  

Para tener información de que es un NAOVA y como hacerlo en R puede ir al siguiente enlace [Prueba_de_ANOVA]()

[ANOVA_EXCEL](https://www.excel-easy.com/examples/anova.html)
[ANOVA-Google_Sheet](https://www.statology.org/one-way-anova-google-sheets/)


## Trabajo para entregar

### Tema a desarrolla diversidad morfológica entre individuos.

Preguntas para considerar en su trabajo.
  - donde proviene la variación entre individuos.
  - a que escala uno puede medir la variación
  - cuan grande es la variación observada entre diferentes escalas (por ejemplo entre individuos)
  - como se compara con la información en la literatura.
  
  

1. El reporte tiene que incluir todas las partes en orden
2. El desarrollo del tema debería tener una secuencia lógica
3. Gráficos y/o tablas tienen que ser adecuadas


Recuerda que no se enseña los datos originales, pero los analisis.  





 



