---
title: "CODIGO DE HONOR"
author: "Raymond L. Tremblay"
date: "8/2/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Cláusulas del Código de Honor de UPRH 

- Usted se responsabiliza totalmente por el uso adecuado y ético de su cuenta de acceso a Moodle que la UPR le da, mientras estudia en la Institución. 
- Usted se compromete a utilizar el contenido del curso únicamente con propósitos académicos y no con el fin de obtener algún lucro, duplicación o beneficio personal sin la debida autorización. 
- Usted debe cumplir con lo expuesto en el bosquejo del curso que le entrega el profesor, documento que responde al prontuario departamental del curso, y con las actividades de aprendizaje contenidas en la plataforma Moodle 
- Usted se compromete a realizar/tomar toda prueba en línea y presencial sin incurrir en actos indebidos tales como: copiarse, recibir ayuda de compañeros de clase o de otras personas. 
- Usted reconoce que posee una cuenta oficial que se le facilita cuando es admitido al sistema de la UPR. Esta tiene su nombre de usuario y una contraseña, que le permitirá tener acceso a: correo electrónico, al portal y la plataforma institucional Moodle. La cuenta autentica al usuario como estudiante de la Universidad de Puerto Rico en Humacao, matriculado en el curso al que accede. Por lo tanto, usted se responsabiliza totalmente por el uso adecuado y ético de su cuenta, mientras estudia en la Institución. El acceso al curso, con su cuenta, por parte de otras personas no matriculadas en este para realizar las actividades instruccionales que usted debe cumplir, es una práctica antiética. Ese acto conlleva acciones disciplinarias/sanciones, según establecido en la normativa institucional y sistémica, Reglamento General de Estudiantes de la UPR, según enmendado en el 2011, Parte B: Sobre la conducta sujeta a sanciones y las medidas disciplinarias. 
- El contenido del curso es propiedad intelectual de la Universidad de Puerto Rico en Humacao. Usted se compromete a utilizar el contenido del curso únicamente con propósitos académicos y no con el fin de obtener algún lucro, duplicación o beneficio personal sin la debida autorización. El uso indebido de ese contenido puede llevar penalidades de carácter disciplinario y legal. Usted podrá acceder a cualquier contenido que esté protegido por la Licencia de Comunes Creativos (Creative Commons). Podrá reproducir, redistribuir ese contenido y a referenciarlos en diversos proyectos o trabajos reconociendo su autoría. 
- Usted debe cumplir con lo expuesto en el prontuario del curso que presenta el profesor. Además, debe cumplir con el contenido del curso (foros de discusión, charlas, informes, tareas, presentaciones, pruebas, exámenes, entre otros) en las fechas establecidas en el calendario. En caso de duda sobre alguna actividad o tarea, debe comunicarse con el profesor previo a la fecha límite establecida del envío o entrega de la actividad/tarea. El no participar en las actividades instruccionales y de evaluación en las fechas establecidas se contará como ausencia o calificación de cero. 
- Usted se compromete a realizar/tomar toda prueba presencial sin incurrir en actos indebidos tales como: copiar total o parcialmente la labor académica de otra persona, plagiar total o parcialmente el trabajo de otra persona, copiar total o parcialmente las respuestas de otra persona a las preguntas de un examen, haciendo o consiguiendo que otro tome en su nombre cualquier prueba o examen oral o escrito, así como la ayuda o facilitación para que otra persona incurra en la referida conducta. El profesor posee la facultad para cuestionar al estudiante si detecta alguna irregularidad en la prueba realizada. Además, usted se compromete a realizar las actividades de aprendizaje sin incurrir en actos mencionados, pues el cumplimiento con el criterio de Integridad Académica no es negociable. 
- Usted debe poseer las destrezas básicas del uso de las computadoras e informática para participar en el curso. De no poseerlas, se compromete a solicitar servicios de tutoría sobre el manejo de las herramientas de la plataforma. El desconocimiento tecnológico no exime al estudiante del cumplimiento de sus responsabilidades académicas, sobre todo, porque esas destrezas son requisitos para matricularse en el curso. 
- Usted cuenta con el equipo identificado como necesario (computadora, acceso a la Internet y cámara, entre otros) para cumplir con los objetivos del curso. De no poseer estos, puede hacer uso de los equipos disponibles en la Institución, pero estarán limitados al horario de servicio de estos. Esto no representa una excusa para que evada el cumplimiento de las tareas. Se recomienda utilizar dispositivos de almacenamiento así como los servicios de almacenamiento en red para evitar la pérdida de información o de sus trabajos. Usted es responsable del funcionamiento y mantenimiento de su equipo personal y de crear/guardar copia de su desempeño. Se recomienda el uso del Google Drive institucional correo UPR y de otros servicios de almacenamiento en la nube (Dropbox, Slideshare, Scrib o Box.net, entre otros). También se exhorta el uso de dispositivos de memoria externa como recursos de resguardo. El profesor se reserva el derecho de imponer penalidades, de aceptar o no un trabajo, de permitir o no contestar una prueba o un examen, entre otros. 
- Usted es responsable de instalar los programas de navegación, “plug-ins” (Java, Flash), antivirus y herramientas requeridas para acceder a la plataforma Moodle. El no contar con estos no lo excusa de cumplir con la participación y las tareas del curso. Si desconoce cómo instalarlos, puede visitar la Oficina de Sistemas de Información (OSI) en el área de apoyo técnico para solicitar la asistencia requerida. 
- Usted se compromete a mantener comunicación efectiva con el profesor del curso en caso de alguna dificultad técnica o alguna otra situación que le impida realizar a tiempo las actividades interactivas. 
- Usted se compromete en participar en el curso en línea bajo un ambiente de seguridad, respeto y colaboración con los demás compañeros. No se permitirá utilizar un lenguaje ofensivo, discriminatorio, despectivo o amenazante hacia los compañeros de clase y del profesor. 
- En caso de interrupciones o averías en la red de comunicación institucional que impidan a usted cumplir con la participación en el curso, por ejemplo en foros, y con el envío de los trabajos, el profesor informará cómo atenderá la situación. 
- Usted tiene derecho a conocer sus calificaciones en el tiempo establecido por reglamentación institucional. Además, tiene derecho a solicitar un Incompleto, pero el profesor se reserva el derecho de otorgarlo. El procedimiento se encuentra definido en la Certificación Número 1998-99-53 del Senado Académico de UPRH: Normas Académicas de la Universidad de Puerto Rico en Humacao. (Enmendada el jueves 16 de mayo de 2002 [Cert Número 2001-02-80]). 
- Aquellos de ustedes que confronten dificultades con el acceso al curso en línea es importante que acuda a la Oficina de Educación a Distancia para solicitar apoyo técnico.
