---
title: "COVID-19"
author: "Raymond L. Tremblay"
date: "8/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Reglas de seguridad a seguir durante la emergencia del Covid-19 en los laboratorios de Biología

- A la luz de la situación generada por el COVID-19 el personal del Departamento de Biología ha generado una guía de seguridad con el fin de proveer las condiciones para obtener una zona de trabajo segura en las actividades que se realizan en nuestros laboratorios.
- Seguridad en áreas de preparación de materiales, instrumentación de uso común y laboratorios académicos
- Para mantener la seguridad el personal técnico adscrito al Departamento de Biología estará realizando la tarea de desinfectar las áreas de los laboratorios académicos utilizando las recomendaciones del CDC. Esto implica que los equipos e instrumentos de uso común y superficies de contacto serán limpiadas y desinfectadas con los detergentes recomendados por la FDA.
- Reglas de seguridad en los Laboratorios Académicos. Tanto profesor como estudiante seguirán las reglas de seguridad vigentes de los laboratorios académicos (adjunto). A su vez incluirán las siguientes medidas de movilidad, organización y limpieza de equipo y zona de trabajo.
- Los estudiantes esperarán en sus vehículos hasta su hora de laboratorio. Al salir del vehículo se colocarán su mascarilla. Deberán llegar a la zona del laboratorio 5 minutos antes del inicio, manteniendo el distanciamiento requerido (según las áreas designadas en el pasillo). Sólo llevarán al laboratorio los materiales necesarios para realizar la práctica.
- Justo antes de entrar al laboratorio se pondrán su equipo de seguridad personal. Incluye: bata de laboratorio y gafas de seguridad.
- El técnico de laboratorio o el profesor le tomará la temperatura al estudiante antes de entrar al laboratorio.
- Al entrar, colocará sus materiales personales en el área designada e inmediatamente deberá lavarse las manos y desinfectarlas con “hand sanitizer”.
- Luego se colocará los guantes y procederá a limpiar las superficies con Lysol. Incluye: la mesa de trabajo y su silla.
- Cualquier equipo utilizado deberá ser desinfectado antes y después de utilizarlo con alcohol al 70%. Incluye: microscopios, micropipetas, pipeteadores, vortex, balanzas, centrífugas, huesos, laminillas, tubos de ensayo, etc.
- No podrán quitarse la mascarilla, ni ningún elemento de seguridad personal mientras esté en el laboratorio.
 

  
- Evitará las salidas innecesarias del laboratorio. Toda persona que abandone el salón durante el periodo de laboratorio deberá realizar todo el proceso desinfección nuevamente y mantendrá la bata de laboratorio dentro del salón.
- Al finalizar el laboratorio descartarán los guantes en el área correspondiente y se lavarán las manos nuevamente.
- Una vez completado el laboratorio los estudiantes
- Deberán firmar un documento que certifique que han leído y discutido estas reglas con
su profesor.


## Limpieza de los Microscopios

- Utilizar gafas de seguridad.
- Limpiar el microscopio antes y después de cada uso.
- Para limpiar el cuerpo del microscopio se utiliza alcohol 90%. El alcohol 70% es
igualmente aceptable.
- En la óptica (todo lo que es cristal), se utiliza alcohol 70%. Un porcentaje mayor puede
dañar la óptica.
- Para fines de los laboratorios en el Departamento de Biología, se recomienda utilizar
alcohol 70% para limpiar todo el microscopio. Colocar el alcohol en un atomizador, no botella de lavado. Con el atomizador hay mayor control de la cantidad de líquido que se utiliza.
- El "kimwipes" es recomendado para limpiar el microscopio, no utilizar servilleta. No se recomienda que el papel esté muy empapado con alcohol 70%. No rociar con alcohol el microscopio, sino el papel de lente o "kimwipes".
- Para los oculares se utiliza papel de lente o "cotton swabs" (Q-tips). No es recomendable que sea con palito de madera, preferible palito de cartón.
- Si el objetivo tiene aceite de inmersión, con un extremo del "cotton swabs" se absorbe o limpia el aceite y con el otro extremo se coloca alcohol 70% para limpiarlo. Si no está disponible, puede realizarlo con papel de lente.
Medidas para mantener el distanciamiento en los laboratorios:
- El acceso al laboratorio se realizará de forma unidireccional. Se usará una sola puerta para entrar y otra para salir. Las puertas estarán identificadas a estos fines.
- El laboratorio tendrá disponible solo las sillas necesarias para realizar el trabajo, contemplando el distanciamiento social.
- Las estaciones de trabajo estarán identificadas en la superficie de las mesas.
- Se utilizarán divisiones en acrílicos en las estaciones para separar a las zonas de trabajo
de los estudiantes.
- El microscopio será utilizado por el estudiante encargado, no se permite rotación entre
estudiantes. Si desea mostrar la imagen de lo que está observando al profesor tomará una foto y se la mostrará. Deberá limpiar el ocular con etanol antes y después de sus observaciones.
 
## Responsabilidad del Profesor:

- El profesor también cumplirá con la observación e implementación de todas las reglas de seguridad.
- El profesor llegará con tiempo suficiente para asegurar que todo está organizado en el laboratorio.
- Al finalizar la sesión, el profesor se asegurará que todo queda debidamente limpio, desinfectado y organizado en el laboratorio.

### IMPORTANTE: Este protocolo de reglas descritas se suma a las Reglas de Seguridad ya presentes en los laboratorios del Departamento de Biología.
 
 
 DEPARTAMENTO DE BIOLOGÍA
UNIVERSIDAD DE PUERTO RICO EN HUMACAO, CALL BOX 860 HUMACAO, PUERTO RICO 00792 

- www.uprh.edu
- T 787.850.9388/9497 F 787.850.9439 
- Patrono con igualdad de Oportunidades de Empleo 
- www.uprh.edu /biología/