---
title: "NORMAS DE SEGURIDAD"
author: "Laboratorios"
date: "Agosto 2021"
output:
  html_document:
    theme: spacelab
    toc: yes
    toc_float: yes
    code_folding: hide
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

NORMAS DE SEGURIDAD EN EL LABORATORIO

Normas generales

- No fumes, comas o bebas en el laboratorio.
- Utiliza una bata y ten la misma siempre bien abrochada, así protegerás tu ropa y piel.
- Guarda tus prendas y los objetos personales en una gaveta o armario, y no los dejes nunca so­bre la mesa de trabajo o el pasillo.
- No corras dentro del laboratorio.
- Si tienes el cabello largo, usa algún método para mantenerlo recogido.
- Dispón sobre la mesa sólo los libros, cuadernos o materiales que sean necesarios.
- Ten siempre tus manos limpias y secas. Si tienes alguna herida, cubre la misma.
- No pruebes ni ingieras los productos o materiales vegetales o de trabajo.
- En caso de producirse un accidente, quemadura o lesión, comunícalo inmediatamente al profesor o técnico.
- Mantén el área de trabajo limpia y ordenada.

- Normas para manipular instrumentos y productos

- Antes de manipular un aparato o montaje eléctrico (microscopio, p. ej.), desconecta el mismo de la red eléctrica.
- Transporta el microscopio utilizando ambas manos, una siempre por debajo.
No utilices el microscopio si no conoces o recuerdas sus funciones. Pregunta al profesor.
- Maneja con especial cuidado el material frágil, por ejemplo, el vidrio.
- Informa al profesor del material roto o averiado.
- Fíjate en los signos de peligrosidad que aparecen en los frascos de los productos químicos.
- Lávate las manos con jabón después de tocar cualquier producto químico o material vegetal.
- Al acabar la práctica, limpia y ordena el material utilizado.
- Si te salpicas accidentalmente, lava la zona afectada con agua abundante. Si salpicas la mesa, limpia con agua y seca después con un paño.
- Evita el contacto con fuentes de calor. No manipules cerca de ellas sustancias inflamables. Para sujetar el instrumental de vidrio y retirarlo del fuego, utiliza pinzas de madera. Cuando calientes los tubos de ensayo con la ayuda de dichas pinzas, procura darles cierta inclinación. Nunca mires directamente al interior del tubo por su abertura ni dirijas esta hacia algún compañero.
- Todos los productos inflamables deben almacenarse en un lugar adecuado y separados de los ácidos, las bases y los reactivos oxidantes.
- Los ácidos y las bases fuertes han de manejarse con mucha precaución, ya que la mayoría son corrosivos y, si caen sobre la piel o la ropa, pueden producir heridas y quemaduras importantes.
- Si tienes que mezclar algún ácido (por ejemplo, ácido sulfúrico) con agua, añade el ácido sobre el agua, nunca al contrario, pues el ácido salpicaría y podría provocar quemaduras en la cara y los ojos.
- No dejes destapados los frascos, ni aspires su contenido. Muchas sustancias líquidas (alcohol, éter, cloroformo, amoníaco...) emiten vapores tóxicos.

## Alarmas

- Al sonar una alarma debe abandonar el laboratorio de manera ordenada, y dirigirse al lugar de encuentro según indicado en el Plan de Emergencia de la UPRH.

## MEDIDAS DE PRECAUCIÓN PARA MITIGAR LOS EFECTOS DE UN TERREMOTO

(tomado de Red Sísmica de Puerto Rico: http://redsismica.uprm.edu/Spanish/informacion/sisnotas_med.php )

## Durante el sismo:

1. Reaccione con prontitud.
2. Si está dentro de una edificación, quédese ahí y muévase a un lugar seguro (preferiblemente ya identificado).
3. Manténgase alejado de objetos peligrosos y ventanas, y protéjase contra los que puedan caer.
4. No corra. En la mayoría de los casos es más seguro quedarse adentro que tratar de salir.
5. No use el elevador o trate de salir por las escaleras durante el terremoto.
6. Si está fuera, quédese ahí, alejándose de postes, árboles y edificios.
7. Si está en un sillón de ruedas, quédese en él y trate de esquivar objetos que puedan estar cayendo.

## Después del sismo:

1. Salga con cuidado del lugar, si se encuentra dentro de una edificación.
2. Aléjese del mar (viaje de campo, p. ej.)
3. Mantenga la calma, tome unos momentos para pensar las consecuencias de lo que vaya a
     Hacer.
4. Diríjase al lugar indicado en el Plan de Emergencia UPRH.
5. No haga llamadas innecesarias.
6. No toque cables o postes eléctricos que hayan caído al suelo.
7. Esté preparado para más temblores.
8. Si está inmovilizado o atrapado, llame o haga ruido para recibir ayuda.
9. Si usted es sordo o tiene problemas auditivos, atraiga la atención de otros.
10. Ayude a las personas con impedimentos visuales.
11. Siga las instrucciones de las personas a cargo de acuerdo al Plan de emergencia de la UPRH.
